# Generated by scripts/gen_plugin_sdk_types.py; do not edit.
from __future__ import annotations

from typing import Any, Literal, TypedDict


class _PrincipalContextRequired(TypedDict):
    id: str
    display_name: str
    storage_dir: str


class PrincipalContext(_PrincipalContextRequired, total=False):
    roles: list[str]


class _ScopeTypeRequired(TypedDict):
    name: str


class ScopeType(_ScopeTypeRequired, total=False):
    description: str


class _ToolDefRequired(TypedDict):
    name: str
    description: str
    parameters: dict[str, Any]
    read_only: bool
    destructive: bool
    gate: Literal["auto", "review", "popup"]


class ToolDef(_ToolDefRequired, total=False):
    scopes: list[str]
    effect: str
    title: str


class _BlockHeadingRequired(TypedDict):
    type: Literal["heading"]
    text: str


class BlockHeading(_BlockHeadingRequired, total=False):
    level: Literal[2, 3]


class BlockFieldsItemsItem(TypedDict):
    label: str
    value: str


class BlockFields(TypedDict):
    type: Literal["fields"]
    items: list[BlockFieldsItemsItem]


class BlockTableColumnsItem(TypedDict):
    key: str
    label: str


class BlockTable(TypedDict):
    type: Literal["table"]
    columns: list[BlockTableColumnsItem]
    rows: list[dict[str, str | int | float | bool | None]]


class BlockText(TypedDict):
    type: Literal["text"]
    text: str


class _BlockCodeRequired(TypedDict):
    type: Literal["code"]
    text: str


class BlockCode(_BlockCodeRequired, total=False):
    language: str


class BlockDiff(TypedDict):
    type: Literal["diff"]
    format: Literal["unified"]
    text: str


Block = BlockHeading | BlockFields | BlockTable | BlockText | BlockCode | BlockDiff


ErrorCode = Literal[
    -32700,
    -32603,
    -32602,
    -32601,
    -32600,
    -32014,
    -32013,
    -32012,
    -32011,
    -32010,
    -32009,
    -32008,
    -32007,
    -32006,
    -32005,
    -32004,
    -32003,
    -32002,
    -32001,
]


ErrorMessage = Literal[
    "parse_error",
    "invalid_request",
    "method_not_found",
    "invalid_params",
    "internal_error",
    "operation_not_allowed",
    "connector_unavailable",
    "unknown_principal",
    "payload_too_large",
    "upstream_error",
    "org_only_field",
    "confirmation_refused",
    "unknown_tool",
    "invalid_blocks",
    "version_mismatch",
    "unknown_call",
    "digest_mismatch",
    "timeout",
    "introspection_only",
]


ErrorDataCode = Literal[
    "parse_error",
    "invalid_request",
    "method_not_found",
    "invalid_params",
    "internal_error",
    "operation_not_allowed",
    "connector_unavailable",
    "unknown_principal",
    "payload_too_large",
    "upstream_error",
    "org_only_field",
    "confirmation_refused",
    "unknown_tool",
    "invalid_blocks",
    "version_mismatch",
    "unknown_call",
    "digest_mismatch",
    "timeout",
    "introspection_only",
]


class ErrorData(TypedDict):
    code: ErrorDataCode
    detail: str
    retryable: bool


class Error(TypedDict):
    code: ErrorCode
    message: ErrorMessage
    data: ErrorData


ManifestSourceOperationsItem = Literal[
    "salesforce.report_run",
    "jira.search",
    "drive.download",
    "sheets.get_values",
    "confluence.get_page",
    "calendar.list_events",
]


class _ManifestRequired(TypedDict):
    name: str
    display_name: str
    version: str
    protocol: str
    command: list[str]
    tools: Literal["dynamic"]


class Manifest(_ManifestRequired, total=False):
    source_operations: list[ManifestSourceOperationsItem]
    max_gate_floor: Literal["review", "auto"]
    pages: bool
    service_credentials: bool


class InitializeParamsDaemon(TypedDict):
    name: str
    version: str


class InitializeParamsPlugin(TypedDict):
    name: str
    manifest_version: str


class InitializeParamsLimits(TypedDict):
    max_line_bytes: int
    max_in_flight: int
    inline_result_bytes: int


class InitializeParams(TypedDict):
    protocol_version: str
    purpose: Literal["run", "introspect"]
    mode: Literal["local", "org"]
    daemon: InitializeParamsDaemon
    plugin: InitializeParamsPlugin
    data_dir: str
    principals: list[PrincipalContext]
    limits: InitializeParamsLimits


class InitializeResultPlugin(TypedDict):
    name: str
    version: str


class _InitializeResultRequired(TypedDict):
    protocol_version: str
    plugin: InitializeResultPlugin
    tools: list[ToolDef]


class InitializeResult(_InitializeResultRequired, total=False):
    scope_types: list[ScopeType]


class ToolsChangedParams(TypedDict):
    tools: list[ToolDef]


class ToolPrepareParams(TypedDict):
    call_id: str
    principal: PrincipalContext
    tool: str
    args: dict[str, Any]
    reason: str | None


class _ToolPrepareResultRequired(TypedDict):
    preview: list[Block]


class ToolPrepareResult(_ToolPrepareResultRequired, total=False):
    payload: list[Block]
    scopes: dict[str, list[str]]


class ToolExecuteParamsApproval(TypedDict):
    approval_id: str
    decision: Literal["approved"]
    via: Literal["card", "rule", "auto"]
    decided_at: str


class ToolExecuteParams(TypedDict):
    call_id: str
    principal: PrincipalContext
    tool: str
    args: dict[str, Any]
    args_digest: str
    approval: ToolExecuteParamsApproval


class ToolExecuteResult(TypedDict, total=False):
    result: Any
    approval_id: str


SourceCallParamsOperation = Literal[
    "salesforce.report_run",
    "jira.search",
    "drive.download",
    "sheets.get_values",
    "confluence.get_page",
    "calendar.list_events",
]


class _SourceCallParamsRequired(TypedDict):
    principal: str
    operation: SourceCallParamsOperation


class SourceCallParams(_SourceCallParamsRequired, total=False):
    params: dict[str, Any]
    credential: Any


class SourceCallResult(TypedDict):
    operation: str
    data: Any
    bytes: int
    next_cursor: str | None


class _ConfirmRequestParamsRequired(TypedDict):
    principal: str
    kind: str
    title: str
    preview: list[Block]


class ConfirmRequestParams(_ConfirmRequestParamsRequired, total=False):
    require_step_up: bool


class ConfirmRequestResult(TypedDict):
    approval_id: str
    expires_at: str


class _ConfirmAwaitParamsRequired(TypedDict):
    approval_id: str


class ConfirmAwaitParams(_ConfirmAwaitParamsRequired, total=False):
    timeout_ms: int


class _ConfirmAwaitResultRequired(TypedDict):
    status: Literal["approved", "denied", "expired"]


class ConfirmAwaitResult(_ConfirmAwaitResultRequired, total=False):
    decided_at: str


class WebRequestParams(TypedDict):
    principal: PrincipalContext
    method: Literal["GET"]
    path: str
    query: dict[str, str]


class _WebRequestResultRequired(TypedDict):
    status: int
    body: str


class WebRequestResult(_WebRequestResultRequired, total=False):
    headers: dict[str, str]
    body_encoding: Literal["utf8", "base64"]


class _StoragePurgeParamsRequired(TypedDict):
    scope: Literal["all", "install", "principal"]


class StoragePurgeParams(_StoragePurgeParamsRequired, total=False):
    principal: str


class StoragePurgeResult(TypedDict):
    purged: Literal[True]


class ConnectorStateChangedParams(TypedDict):
    connector: str
    state: Literal["enabled", "disabled", "signed_in", "signed_out"]
    principal: str


class PrincipalRemovedParams(TypedDict):
    principal: str


class PluginDisablingParams(TypedDict):
    reason: Literal["user", "crash_limit", "hash_changed", "admin"]


class ShutdownParams(TypedDict):
    grace_ms: int
