#!/usr/bin/env python3
"""Generate the plugin SDK's protocol types from the protocol's JSON Schema.

Reads ``docs/plugin-protocol/protocol.schema.json`` and writes
``plugin-sdk/src/privacyfence_plugin_sdk/types.py``: one ``TypedDict`` per ``$defs`` entry (plus one
per nested object), ``total=False`` for the optional keys, ``Literal`` for enums and constants.
Stdlib only.

``--check`` writes nothing: it exits 1 and prints the first differing line when the checked-in file
is stale. ``tests/unit/test_gen_plugin_sdk_types.py`` runs it. The output is already in the shape
``ruff format`` produces, so the check compares bytes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "docs" / "plugin-protocol" / "protocol.schema.json"
OUTPUT_PATH = REPO_ROOT / "plugin-sdk" / "src" / "privacyfence_plugin_sdk" / "types.py"

HEADER = "# Generated by scripts/gen_plugin_sdk_types.py; do not edit."
# Longer Literals move to a named alias so the output needs no line wrapping.
LITERAL_INLINE_MAX = 60

_SCALARS = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "null": "None"}


def _pascal(text: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in text.replace("-", "_").split("_") if part)


def _union(parts: list[str]) -> str:
    unique = list(dict.fromkeys(parts))
    return " | ".join(unique)


class _Generator:
    def __init__(self) -> None:
        self.blocks: list[str] = []

    def _literal(self, values: list[object], name: str) -> str:
        """``Literal[...]``; one too long for a line becomes a module-level alias named ``name``."""
        items = [json.dumps(v) if isinstance(v, str) else repr(v) for v in values]
        inline = "Literal[" + ", ".join(items) + "]"
        if len(inline) <= LITERAL_INLINE_MAX:
            return inline
        body = "".join(f"    {item},\n" for item in items)
        self.blocks.append(f"{name} = Literal[\n{body}]\n")
        return name

    def type_expr(self, schema: dict, name: str) -> str:
        if "$ref" in schema:
            return schema["$ref"].rsplit("/", 1)[-1]
        if "const" in schema:
            return self._literal([schema["const"]], name)
        if "enum" in schema:
            return self._literal(schema["enum"], name)
        if "oneOf" in schema:
            return _union([self.type_expr(s, name + _variant(s, i)) for i, s in enumerate(schema["oneOf"])])
        kind = schema.get("type")
        if isinstance(kind, list):
            return _union([self.type_expr({**schema, "type": k}, name) for k in kind])
        if kind in _SCALARS:
            return _SCALARS[kind]
        if kind == "array":
            return f"list[{self.type_expr(schema.get('items', {}), name + 'Item')}]"
        if kind == "object":
            if "properties" in schema:
                self.typed_dict(name, schema)
                return name
            extra = schema.get("additionalProperties")
            if isinstance(extra, dict):
                return f"dict[str, {self.type_expr(extra, name + 'Value')}]"
            return "dict[str, Any]"
        return "Any"

    def typed_dict(self, name: str, schema: dict) -> None:
        required = set(schema.get("required", []))
        req: list[str] = []
        opt: list[str] = []
        for key, sub in schema["properties"].items():
            line = f"    {key}: {self.type_expr(sub, name + _pascal(key))}"
            (req if key in required else opt).append(line)
        if opt and req:
            self.blocks.append(_class(f"_{name}Required", "TypedDict", req))
            self.blocks.append(_class(name, f"_{name}Required, total=False", opt))
        elif opt:
            self.blocks.append(_class(name, "TypedDict, total=False", opt))
        else:
            self.blocks.append(_class(name, "TypedDict", req or ["    pass"]))

    def alias(self, name: str, schema: dict) -> None:
        expr = self.type_expr(schema, name if "oneOf" in schema else name + "Value")
        self.blocks.append(f"{name} = {expr}\n")


def _variant(schema: dict, index: int) -> str:
    tag = schema.get("properties", {}).get("type", {}).get("const")
    return _pascal(tag) if isinstance(tag, str) else str(index + 1)


def _class(name: str, bases: str, body: list[str]) -> str:
    return f"class {name}({bases}):\n" + "\n".join(body) + "\n"


def render(schema: dict) -> str:
    gen = _Generator()
    for name, sub in schema["$defs"].items():
        if sub.get("type") == "object" and "properties" in sub:
            gen.typed_dict(name, sub)
        else:
            gen.alias(name, sub)
    head = f"{HEADER}\nfrom __future__ import annotations\n\nfrom typing import Any, Literal, TypedDict\n"
    return head + "\n\n" + "\n\n".join(gen.blocks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--schema", type=Path, default=SCHEMA_PATH, help="the protocol JSON Schema to read")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH, help="the types module to write or check")
    parser.add_argument("--check", action="store_true", help="exit 1 if the output file is stale; write nothing")
    args = parser.parse_args(argv)

    text = render(json.loads(args.schema.read_text(encoding="utf-8")))
    if not args.check:
        args.output.write_text(text, encoding="utf-8")
        return 0
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if current == text:
        return 0
    old, new = current.splitlines(), text.splitlines()
    for number in range(max(len(old), len(new))):
        a = old[number] if number < len(old) else "<end of file>"
        b = new[number] if number < len(new) else "<end of file>"
        if a != b:
            print(f"{args.output}: stale at line {number + 1}\n  have: {a}\n  want: {b}", file=sys.stderr)
            break
    print("Run: python3 scripts/gen_plugin_sdk_types.py", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
