"""Drift guard for docs/tools-reference.md.

The doc is generated by scripts/generate_tools_reference.py from the connectors' own tool
definitions and auto_accept.TOOL_TO_GATE, so it can only be wrong by being stale. This test is what
enforces "don't hand-edit it": a connector that gains, loses or re-gates a tool, or changes a tool's
description, without the generator being re-run fails CI here.

The targeted assertions below pin properties a reader relies on and that a generator bug could
break while still producing a self-consistent file: counts are computed, gates match the gate
table, and the header says the file is generated.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import generate_tools_reference as gen  # noqa: E402

from privacyfence.auto_accept import TOOL_TO_GATE  # noqa: E402

_ROW_RE = re.compile(r"^\| `([a-z0-9_]+)` \| (read|write) \| `(auto|review|popup)` \|", re.MULTILINE)


def test_checked_in_doc_matches_a_fresh_generation():
    checked_in = gen.DOC_PATH.read_text(encoding="utf-8")
    fresh = gen.render()
    assert checked_in == fresh, (
        "docs/tools-reference.md is stale -- run `python scripts/generate_tools_reference.py` "
        "and commit the result."
    )


def test_header_says_the_file_is_generated():
    doc = gen.render()
    assert "GENERATED FILE" in doc
    assert "scripts/generate_tools_reference.py" in doc


def test_every_gated_tool_has_exactly_one_row_with_its_gate():
    rows = {tool: gate for tool, _direction, gate in _ROW_RE.findall(gen.render())}
    assert rows == TOOL_TO_GATE


def test_total_row_is_computed_from_the_gate_table():
    doc = gen.render()
    counts = {gate: sum(1 for g in TOOL_TO_GATE.values() if g == gate) for gate in gen.GATE_ORDER}
    expected = (
        f"| **Total** | **{len(TOOL_TO_GATE)}** | "
        + " | ".join(f"**{counts[gate]}**" for gate in gen.GATE_ORDER)
        + " |"
    )
    assert expected in doc


def test_first_sentence_skips_abbreviations_and_escapes_pipes():
    assert gen.first_sentence("Upload a file (e.g. a PDF) to Drive. Requires approval.") == (
        "Upload a file (e.g. a PDF) to Drive."
    )
    assert gen.first_sentence("Read a | b. More.") == "Read a \\| b."
