"""Content-Security-Policy building blocks shared by every part of the web
app. Deliberately tiny and dependency-free (imports nothing from this package) so both
web/server.py's ``_SecurityHeadersMiddleware`` (which owns actually
emitting the header) and every route/HTML module that renders an inline
``<style>``/``<script>`` tag (which need the *same* nonce value baked into
their own markup) can import it with no risk of a circular import -- most
of those route modules are themselves imported *by* server.py.

**Why a nonce, not a blanket ``'unsafe-inline'``.** ``script-src
'unsafe-inline'; style-src 'unsafe-inline'`` means any HTML-injection bug
anywhere in this app's string-built templates (a missed escape, a future
regression) becomes script execution for free, with no second defense in
the way. A per-response nonce closes
that: only ``<style>``/``<script>`` elements carrying the exact nonce this
response's own ``Content-Security-Policy`` header names are honored, and an
attacker injecting markup into the response body has no way to know that
value in advance. See ADR 0063.

**Why ``style-src-attr`` keeps ``'unsafe-inline'``.** CSP nonces only ever
cover ``<style>``/``<script>`` *elements* -- there is no nonce mechanism for
an inline ``style="..."`` *attribute* (CSP3's answer for those is
``'unsafe-hashes'`` plus a hash of every distinct attribute value, which
does not fit strings built with per-call dynamic content the way this
codebase's ``style="..."`` attributes are). This codebase uses inline style
attributes pervasively for computed, per-value styling (line-clamp heights,
per-tool accent colors) -- rewriting all of them onto CSS classes is a much
larger, purely cosmetic refactor with no bearing on the actual risk this
item targets (arbitrary ``<script>``/``<style>`` *element* injection), so
it's out of scope here. ``style-src-elem`` still gets the same nonce
treatment as ``script-src``, so an attacker who manages to inject a whole
``<style>`` block (a real vector: CSS-only data exfiltration via attribute
selectors) is still stopped; only the pre-existing, narrower attribute-value
risk (already contained by this policy's ``img-src``/``connect-src``, since
a style attribute alone can't originate a request those don't already
block) is left as it was.
"""
from __future__ import annotations

import secrets
from collections.abc import MutableMapping
from typing import Any

from starlette.requests import Request

# The one key this module ever reads or writes on request.state -- kept
# private so every caller goes through nonce_for()/set_nonce() rather than
# the raw scope key name drifting out of sync between web/server.py and
# whichever route module.
_STATE_KEY = "csp_nonce"
# The two per-response framing flags. Each is set by one route for one response and read by
# _SecurityHeadersMiddleware when it builds that response's headers; neither is ever set by default.
_FRAME_SELF_KEY = "csp_frame_self"
_PLUGIN_EMBED_KEY = "csp_plugin_embed"
_PLUGIN_NEW_TABS_KEY = "csp_plugin_new_tabs"


def new_nonce() -> str:
    """A fresh, cryptographically random nonce value -- base64url text,
    the shape both HTML's ``nonce="..."`` attribute and CSP's
    ``'nonce-...'`` source expression expect."""
    return secrets.token_urlsafe(18)


def nonce_for(request: Request) -> str:
    """The current response's CSP nonce. In every real deployment this was
    already set into ``request.state`` by web/server.py's
    ``_SecurityHeadersMiddleware`` before any route ran -- see that class's
    own docstring. Falls back to minting an unenforced one when that
    middleware isn't in front of this request at all (several route
    modules' own unit tests build a bare ``create_app()`` directly, with
    none of server.py's middleware stack a real ``WebServer`` always wraps
    it in), so a page rendered under test still comes out as valid markup
    instead of raising."""
    return getattr(request.state, _STATE_KEY, None) or new_nonce()


def set_nonce(request: Request, nonce: str) -> None:
    """Override this response's nonce. For a document that was rendered
    once, well before this particular response existed (approval_window_
    html.py's/dialog_window_html.py's card and dialog documents, reused
    across every ``GET`` of the same approval until it's decided -- see
    that module's own docstring), the nonce is fixed at render time, not
    at request time -- the route serving it back (web/routes_approvals.py's
    ``show_approval``, which serves both modes) calls
    this to make the ``Content-Security-Policy`` header
    ``_SecurityHeadersMiddleware`` is about to emit match whatever nonce is
    already baked into that document's body, instead of the fresh
    per-request one generated by default."""
    setattr(request.state, _STATE_KEY, nonce)


def _state_flag(scope_or_request: Request | MutableMapping[str, Any], key: str) -> bool:
    scope = scope_or_request.scope if isinstance(scope_or_request, Request) else scope_or_request
    state = scope.get("state")
    return isinstance(state, MutableMapping) and state.get(key) is True


def set_frame_self(request: Request) -> None:
    """Let this one response's document frame same-origin pages (``frame-src data: 'self'``).
    web/routes_approvals.py's ``show_approval`` sets it only for a plugin approval card that frames
    the plugin's own page; every other response keeps ``frame-src data:``."""
    setattr(request.state, _FRAME_SELF_KEY, True)


def frame_self_for(scope_or_request: Request | MutableMapping[str, Any]) -> bool:
    """Whether ``set_frame_self`` was called for this response. Takes the ``Request`` or, as the
    middleware has it, the raw ASGI scope."""
    return _state_flag(scope_or_request, _FRAME_SELF_KEY)


def set_plugin_embed(request: Request) -> None:
    """Let this one ``/plugins/`` response be framed by a same-origin document: the middleware
    sends plugins/pages.py's ``CSP_EMBEDDED`` and ``X-Frame-Options: SAMEORIGIN`` instead of
    ``CSP`` and ``DENY``. web/routes_plugins.py sets it only for the page a pending approval card
    frames."""
    setattr(request.state, _PLUGIN_EMBED_KEY, True)


def plugin_embed_for(scope_or_request: Request | MutableMapping[str, Any]) -> bool:
    """Whether ``set_plugin_embed`` was called for this response."""
    return _state_flag(scope_or_request, _PLUGIN_EMBED_KEY)


def set_plugin_new_tabs(request: Request) -> None:
    """Let this one ``/plugins/`` response's page open links in new tabs: the middleware sends
    plugins/pages.py's ``CSP_NEW_TABS`` instead of ``CSP``. web/routes_plugins.py sets it only for a
    plugin whose manifest sets ``page_new_tabs``."""
    setattr(request.state, _PLUGIN_NEW_TABS_KEY, True)


def plugin_new_tabs_for(scope_or_request: Request | MutableMapping[str, Any]) -> bool:
    """Whether ``set_plugin_new_tabs`` was called for this response."""
    return _state_flag(scope_or_request, _PLUGIN_NEW_TABS_KEY)


def build_csp(nonce: str, *, app_origin: str = "", frame_self: bool = False) -> str:
    """The full policy for a fully self-contained document (see
    approval_window_html.py's own module docstring: fonts/icons/PDFs are
    base64 ``data:`` URIs, never a network fetch) -- ``default-src 'none'``
    with narrow, explicit exceptions for exactly what these pages actually
    use.

    ``object-src data:`` *and* ``frame-src data:``: without an explicit
    exception, each falls back to ``default-src 'none'`` and blocks
    approval_window_html.build_preview_body_html's own
    ``<embed type="application/pdf" src="data:...">`` -- the PDF-preview
    pane does not render in a real browser without them, and
    ``TestClient``'s in-process transport can't show that because it
    doesn't enforce CSP at all. Both directives, not just ``object-src``, turned
    out to matter: Chromium's built-in PDF viewer renders an ``<embed>``
    by navigating an internal frame, which ``frame-src`` (not just
    ``object-src``) governs -- caught only by actually driving this in a
    real browser (tests/integration/test_browser_smoke.py's
    ``TestPdfPreview``) and reporting the exact violated directive via a
    ``securitypolicyviolation`` listener, not by reasoning about the CSP
    spec from the ``<embed>`` tag alone.

    ``worker-src 'self'`` registers resources/sw.js for tier-0/1
    notifications (web_shell.py's own script) against that same
    default-src 'none'.

    See this module's own docstring for why ``script-src``/``style-src-elem``
    take a nonce while ``style-src-attr`` keeps ``'unsafe-inline'``.

    ``app_origin`` is org mode's own origin (``issuer_url``), given only by org mode's app: it
    adds ``manifest-src 'self'`` so the org pages' ``<link rel="manifest">`` loads (ADR 0081), and
    widens ``img-src`` by exactly the manifest's icon folder, ``<origin>/icons/``, for a browser
    that fetches manifest icons under the page's policy. Local mode links no manifest, so its
    policy stays as it was.

    ``form-action`` follows the same split (ADR 0082). Org mode's ``/connect`` posts native forms
    back to this app (sign-out, and each Telegram step), so its policy allows ``'self'``, and
    nothing wider: every one of those submissions, redirects included, ends on this origin (a
    sign-out lands on ``/signed-out``, not on ``/login``'s bounce to the IdP), and browsers check
    ``form-action`` on each redirect a submission follows. Local mode renders no native form at
    all, so it keeps ``'none'``.

    ``frame_self`` adds ``'self'`` to ``frame-src`` and changes nothing else: a plugin approval
    card frames that plugin's page from this origin (``set_frame_self``). Whether the page agrees
    to be framed is its own response's ``frame-ancestors``, which only the matching card's page
    loosens (``set_plugin_embed``).
    """
    form_action = "'self'" if app_origin else "'none'"
    img_src = f"data: {app_origin.rstrip('/')}/icons/" if app_origin else "data:"
    manifest_src = "manifest-src 'self'; " if app_origin else ""
    frame_src = "data: 'self'" if frame_self else "data:"
    return (
        "default-src 'none'; "
        f"script-src 'nonce-{nonce}'; "
        f"style-src-elem 'nonce-{nonce}'; "
        "style-src-attr 'unsafe-inline'; "
        f"img-src {img_src}; font-src data:; object-src data:; frame-src {frame_src}; "
        "connect-src 'self'; worker-src 'self'; "
        f"{manifest_src}"
        f"base-uri 'none'; form-action {form_action}; frame-ancestors 'none'"
    )


__all__ = [
    "build_csp", "frame_self_for", "new_nonce", "nonce_for", "plugin_embed_for", "plugin_new_tabs_for",
    "set_frame_self", "set_nonce", "set_plugin_embed", "set_plugin_new_tabs",
]
